- name: Install the latest version of Apache
  ansible.builtin.yum:
    name: java
    state: latest

- name: Download tomcat tar
  ansible.builtin.get_url:
    url: "{{TOMCAT_URL}}" 
    dest: /home/ec2-user/
    mode: '0777'

- name: Extract tomcat /home/ec2-user
  ansible.builtin.unarchive:
    src:  /home/ec2-user/{{TOMCAT_ZIP}} 
    dest: /home/ec2-user/
    #remote_src: true

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /home/ec2-user/{{TOMCAT}}/bin/startup.sh
    mode: '0777'

- name: start tomcat
  command: nohup ./startup.sh 
  args:
   chdir: /home/ec2-user/{{TOMCAT}}/bin